concurrent = 1
check_interval = 0
connection_max_age = "15m0s"
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "autopipe-runner"
  url = "http://gitlab"
  id = 1
  token = "glrtr-RdUV9uEHsRN7n8PqdfvP"
  token_obtained_at = 2025-11-26T09:33:52Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "alpine:latest"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    network_mode = "t1_autopipe-net"
    shm_size = 0
    network_mtu = 0
    pull_policy = ["if-not-present", "always"]
    wait_for_services_timeout = 60

[[runners]]
  name = "autopipe-runner"
  url = "http://gitlab"
  id = 2
  token = "glrtr-mq73jmuMBx_R4B8BiwTw"
  token_obtained_at = 2025-11-26T10:55:26Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "alpine:latest"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    network_mode = "t1_autopipe-net"
    shm_size = 0
    network_mtu = 0
    pull_policy = ["if-not-present", "always"]
    wait_for_services_timeout = 60
